config/routes.rb
Wikilicious::Application.routes.draw do
  devise_for :users do
    post "/users/sign_up" => "devise/registrations#create", :as => :sign_up
    post "/users/sign_in" => "devise/sessions#create", :as => :sign_in
    post "/users/password/new" => "devise/passwords#create", :as => :new_password
    put "/users/password/edit" => "devise/passwords#update", :as => :edit_password
  end

  resources :wikis

  root :to => "high_voltage/pages#show", :id => "index"
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :registerable, :validatable, :database_authenticatable, :rememberable,
    :recoverable, :trackable

  has_many :wikis, :foreign_key => :owner_id

  attr_accessible :email, :password, :password_confirmation, :remember_me

  after_create :create_first_wiki

  protected
    def create_first_wiki
      wikis.create(:name => "Misteriously Unnamed Wiki")
    end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  attr_accessible :name, :description

  belongs_to :owner, :class_name => "User"

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => :owner_id, :case_sensitive => :false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wikis_controller.rb
class WikisController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
  def landing_page_is_current_page?
    controller.class == HighVoltage::PagesController and action_name == "show" and
      params[:id] == "index"
  end

  def flash_messages
    messages = ""

    flash.each do |key, value|
      messages << content_tag(:p, value, :class => "#{key} flash_message")
    end

    messages.html_safe
  end

  def class_for_menu
    if landing_page_is_current_page?
      "on_landing_page"
    else
      "not_on_landing_page"
    end
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/application/_menu.html.erb
<div id="menu" class="<%= class_for_menu %>">
  <p>
    <% if not user_signed_in? %>
      <%= link_to "Sign Up", sign_up_path %>
      <span class="menu_items_separator">|</span>
      <%= link_to "Login", sign_in_path %>
    <% else %>
      <%= link_to "Dashboard", sign_up_path %>
      <span class="menu_items_separator">|</span>
      <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
    <% end -%>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>

    <title>Wikilicious</title>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <!--[if IE]>
      <%= stylesheet_link_tag "ie", :media => "all" %>
    <![endif]-->
  </head>
  <body>
    <div id="content">
      <% if not landing_page_is_current_page? %>
        <div id="small_logo">
          <p>
            <%= link_to image_tag("small_logo.png"), root_path %>
          </p>
        </div>
      <% end %>

      <%= render :partial => "menu" %>

      <br clear="all">

      <%= flash_messages %>

      <%= yield %>

      <br clear="all">
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/index.html.erb
<div id="logo">
  <p>
    <%= image_tag "logo.png" %>
  </p>
</div>

<h1 id="marketing_statement">
  The wiki your team deserves!
</h1>

<h2 id="main_features">
  What we have for you
</h2>

<div class="feature">
  <div class="feature_title">
    Markdown to the rescue!
  </div>

  <div class="feature_image"></div>

  <div class="feature_description">
    <p>
      Who needs fancy rich text editors? Here you'll write articles using a really powerful Markdown
      text editor. Like a boss!
    </p>
  </div>
</div>

<div class="feature">
  <div class="feature_title">
    Everybody loves comments!
  </div>

  <div class="feature_image"></div>

  <div class="feature_description">
    <p>
      No need for email. You can suggest improvements on articles simply by commenting on them.
    </p>
  </div>
</div>

<div class="feature">
  <div class="feature_title">
    Only wiki owners need to pay
  </div>

  <div class="feature_image"></div>

  <div class="feature_description">
    <p>
      You can join as many wikis as you want without spend a single penny if none of the them is yours.
    </p>
  </div>
</div>

<div class="feature">
  <div class="feature_title">
    Create as many wikis as you want
  </div>

  <div class="feature_image"></div>

  <div class="feature_description">
    <p>
      No need for being economic. There's no limit on the number of wikis that paid users can create.
    </p>
  </div>
</div>

<br clear="all">

<p class="try_it_container">
  <%= link_to "Try it for free!", sign_up_path %>
</p>